export const EMail_SENT_SUCCESS = 'EMail_SENT_SUCCESS'
export const EMail_SENT_FAILURE = 'EMail_SENT_FAILURE'
export const EMail_SENT_REQUEST = 'EMail_SENT_REQUEST'
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS'
export const PASSWORD_CHANGE_FAILURE = 'PASSWORD_CHANGE_FAILURE'
export const PASSWORD_CHANGE_REQUEST = 'PASSWORD_CHANGE_REQUEST'
export const EMail_SENT_SUCCESS_MESSAGE = "EMail_SENT_SUCCESS_MESSAGE";