export const GET_ORGANISATION_LIST_REQUEST = 'GET_ORGANISATION_LIST_REQUEST'
export const GET_ORGANISATION_LIST_SUCCESS = 'GET_ORGANISATION_LIST_SUCCESS'
export const GET_ORGANISATION_LIST_FAILURE = 'GET_ORGANISATION_LIST_FAILURE'
